import os
from scripts.resources import Resources
from scripts.common import input_samples
from snakemake.utils import min_version

#### set minimum snakemake version ####
min_version("7.2.3")

#### load config ####
configfile: "config/config.yaml"  

#### load genome resources to be used  
resources = Resources(config["ref"]["species"], config["ref"]["build"])

#### get sample names
SAMPLES =  input_samples()
print(SAMPLES)

#### load rules ####
include: "rules/fastqc.smk"
include: "rules/resources.smk"
rule all:
    input:

        resources.ensembl_fasta,
        resources.ensembl_gtf


