import os
from scripts.resources import Resources
from scripts.common import input_samples
from snakemake.utils import min_version

#### set minimum snakemake version ####
min_version("7.2.3")

#### load config ####
configfile: "config/config.yaml"

#### load genome resources to be used
resources = Resources(config["ref"]["species"], config["ref"]["build"])

#### get sample names
SAMPLES =  input_samples()
print(SAMPLES)

#### load rules ####
include: "rules/fastqc.smk"
include: "rules/resources.smk"
include: "rules/trimming.smk"


rule all:
    input:
       # "resources/Homo_sapiens.GRCh38.dna.primary_assembly.fa",
       # "resources/Homo_sapiens.GRCh38.110.chr.gtf",
         "results/qc/multiqc.html",
         "results/trimmed/NC1_R1.fastq.gz"



