import os
from scripts.resources import Resources
from scripts import common as samples
from snakemake.utils import min_version

#### set minimum snakemake version ####
min_version("7.2.3")

#### load config ####
configfile: "config/config.yaml"  

#### load genome resources to be used  
resources = Resources(config["ref"]["species"], config["ref"]["build"])

#### get sample names
SAMPLES =  samples.input_samples()

#### load rules ####
include: "rules/fastqc.smk"

rule all:
    input:
        output.html,
        output.zip

